### ISSUE TITLE
App crashes when browsing GDE directory

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#166]
It crashes sometimes with this stacktrace

java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:299)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
            at java.util.concurrent.FutureTask.run(FutureTask.java:239)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:838)
     Caused by: java.lang.NullPointerException
            at java.util.regex.Matcher.reset(Matcher.java:176)
            at java.util.regex.Matcher.<init>(Matcher.java:89)
            at java.util.regex.Pattern.matcher(Pattern.java:297)
            at org.gdg.frisbee.android.adapter.GdeAdapter$2.doInBackground(GdeAdapter.java:128)
            at org.gdg.frisbee.android.adapter.GdeAdapter$2.doInBackground(GdeAdapter.java:125)
            at org.gdg.frisbee.android.task.CommonAsyncTask.doInBackground(CommonAsyncTask.java:75)
            at android.os.AsyncTask$2.call(AsyncTask.java:287)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:838)

**Comment by joaobiriba** [comment]
Often during the visualization of GDE tabs
