### ISSUE TITLE
App crashes when clicking on a chapter item in Pulse

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#255]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.api.services.plus.model.Person org.gdg.frisbee.android.activity.GdgNavDrawerActivity.getPerson(java.lang.String)' on a null object reference
            at org.gdg.frisbee.android.fragment.InfoFragment$4.doInBackground(InfoFragment.java:124)
            at org.gdg.frisbee.android.fragment.InfoFragment$4.doInBackground(InfoFragment.java:121)
            at org.gdg.frisbee.android.task.CommonAsyncTask.doInBackground(CommonAsyncTask.java:75)
            at android.os.AsyncTask$2.call(AsyncTask.java:288)

**Comment by friedger** [comment]
fixed in #251
