### ISSUE TITLE
Classcast exception

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#272]
From Google Play crash reports:

java.lang.ClassCastException: android.widget.FrameLayout$LayoutParams cannot be cast to android.widget.AbsListView$LayoutParams
at android.widget.ListView.setupChild(ListView.java:1848)
at android.widget.ListView.makeAndAddView(ListView.java:1815)
at android.widget.ListView.fillDown(ListView.java:698)
at android.widget.ListView.fillFromTop(ListView.java:759)

**Comment by tasomaniac** [comment]
I've found the crash. It happens on TaggedEventSeriesFragment on my Genymotion 4.4.2 emulator. It was fine with my Nexus 6.

**Comment by friedger** [comment]
fixed by #280
