### ISSUE TITLE
From Crashlytics: Invalid name to read ModelCache for Gde

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#322]
java.io.IOException: Invalid name: &lt;org.gdg.frisbee.android.api.model.Gde>
       at org.gdg.frisbee.android.cache.ModelCache.readValueFromDisk(ModelCache.java:618)
       at org.gdg.frisbee.android.cache.ModelCache.getFromDiskCache(ModelCache.java:345)
       at org.gdg.frisbee.android.cache.ModelCache.get(ModelCache.java:324)
       at org.gdg.frisbee.android.cache.ModelCache$1.doInBackground(ModelCache.java:274)
       at org.gdg.frisbee.android.cache.ModelCache$1.doInBackground(ModelCache.java:270)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by tasomaniac** [comment]
I was thinking of getting rid of ModelCache and use server cache parameters. 
And in places in which we cannot change server parameters, we can use OKHttp interceptors to override headers to have automatic caching.

What do you think?

**Comment by tasomaniac** [comment]
Closed in #346
