### ISSUE TITLE
From Crashalytics: Unable to resolve host developers.google.com

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#323]
retrofit.RetrofitError: Unable to resolve host "developers.google.com": No address associated with hostname
       at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395)
       at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
       at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
       at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at retrofit.Platform$Android$2$1.run(Platform.java:142)
       at java.lang.Thread.run(Thread.java:818)
Caused by: java.net.UnknownHostException: Unable to resolve host "developers.google.com": No address associated with hostname
       at java.net.InetAddress.lookupHostByName(InetAddress.java:457)
       at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
       at java.net.InetAddress.getAllByName(InetAddress.java:215)
       at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
       at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:224)
       at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:193)
       at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:113)
       at com.squareup.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:344)
       at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:329)
       at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:319)
       at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
       at com.squareup.okhttp.Call.getResponse(Call.java:271)
       at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
       at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
       at com.squareup.okhttp.Call.execute(Call.java:79)
       at retrofit.client.OkClient.execute(OkClient.java:53)
       at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
       at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
       at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
       at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at retrofit.Platform$Android$2$1.run(Platform.java:142)
       at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
       at libcore.io.Posix.android_getaddrinfo(Posix.java)
       at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
       at java.net.InetAddress.lookupHostByName(InetAddress.java:438)
       at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
       at java.net.InetAddress.getAllByName(InetAddress.java:215)
       at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
       at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:224)
       at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:193)
       at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:113)
       at com.squareup.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:344)
       at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:329)
       at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:319)
       at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
       at com.squareup.okhttp.Call.getResponse(Call.java:271)
       at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
       at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
       at com.squareup.okhttp.Call.execute(Call.java:79)
       at retrofit.client.OkClient.execute(OkClient.java:53)
       at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
       at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
       at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
       at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at retrofit.Platform$Android$2$1.run(Platform.java:142)
       at java.lang.Thread.run(Thread.java:818)

**Comment by tasomaniac** [comment]
We are sending logs to Crashlytics. Is it really a crash or is it just an error?

**Comment by Splaktar** [comment]
Looks like it is just an error log from the network being disconnected.

**Comment by tasomaniac** [comment]
It is not a crash right? We log everything with Crashlytics.

**Comment by Splaktar** [comment]
Doesn't look like a crash. This can probably be closed.

**Comment by tasomaniac** [comment]
I doesn't look like a crash. Please reopen this if you think it should stay open.
