### ISSUE TITLE
ModelCache ClassCastException

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#354]
This time it is for EventList in the main screen. I don't know how this happened. I solved it by cleaning data of the app and it is now working fine. 

The crash was persistent and was happening on every app open. 

```
java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to org.gdg.frisbee.android.api.model.SimpleEvent
            at org.gdg.frisbee.android.adapter.EventAdapter.addAll(EventAdapter.java:77)
            at org.gdg.frisbee.android.eventseries.GdgEventListFragment$2.onGet(GdgEventListFragment.java:73)
            at org.gdg.frisbee.android.cache.ModelCache$1.onPostExecute(ModelCache.java:277)
            at android.os.AsyncTask.finish(AsyncTask.java:636)
            at android.os.AsyncTask.access$500(AsyncTask.java:177)
            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by Splaktar** [comment]
This bug is causing a lot of crashes for users and needs to be addressed. Up to 59 crashes so far from this bug via Fabric.io.

    java.lang.ClassCastException: com.google.gson.b.j cannot be cast to org.gdg.frisbee.android.api.model.SimpleEvent
       at org.gdg.frisbee.android.adapter.EventAdapter.addAll(EventAdapter.java:77)
       at org.gdg.frisbee.android.eventseries.GdgEventListFragment$2.onGet(GdgEventListFragment.java:73)
       at org.gdg.frisbee.android.cache.ModelCache$1.onPostExecute(ModelCache.java:277)
       at android.os.AsyncTask.finish(AsyncTask.java:632)
       at android.os.AsyncTask.access$600(AsyncTask.java:177)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5942)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

**Comment by tasomaniac** [comment]
This is a hard one. :(

**Comment by friedger** [comment]
fixed by https://github.com/gdg-x/frisbee/commit/588b9cf1615e3be6165ff63f0cd6ce94f89fc850
