### ISSUE TITLE
getCoverPhoto() on a null object reference

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/frisbee#367]
This has caused 53 crashes via Fabric.io.

    java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.api.services.plus.model.Person$Cover$CoverPhoto com.google.api.services.plus.model.Person$Cover.getCoverPhoto()' on a null object reference
       at org.gdg.frisbee.android.activity.GdgNavDrawerActivity$2.onPostExecute(GdgNavDrawerActivity.java:290)
       at org.gdg.frisbee.android.activity.GdgNavDrawerActivity$2.onPostExecute(GdgNavDrawerActivity.java:285)
       at org.gdg.frisbee.android.task.CommonAsyncTask.onPostExecute(CommonAsyncTask.java:88)
       at android.os.AsyncTask.finish(AsyncTask.java:636)
       at android.os.AsyncTask.access$500(AsyncTask.java:177)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by friedger** [comment]
fixed by abd7fdc10d533c2cc6d24c3c438ec1d3b6b2de21
