### ISSUE TITLE
Arrow game crash after sign out of G+

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/frisbee#401]
1. Go to Arrow game while signed into G+
2. Open Settings and uncheck box to sign out of G+
3. Press Back, You are taken to Arrow Game again
4. Press Crown icon (Achievements), app crashes

If the user is signed out of the Arrow game onResume, we should probably finish the activity and take them back to their previous activity.

    07-25 13:38:46.481  15211-15211/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.gdg.frisbee.android.debug, PID: 15211
    java.lang.IllegalStateException: GoogleApiClient must be connected.
            at com.google.android.gms.common.internal.zzu.zza(Unknown Source)
            at com.google.android.gms.games.Games.zzb(Unknown Source)
            at com.google.android.gms.games.Games.zzd(Unknown Source)
            at com.google.android.gms.games.internal.api.LeaderboardsImpl.getLeaderboardIntent(Unknown Source)
            at com.google.android.gms.games.internal.api.LeaderboardsImpl.getLeaderboardIntent(Unknown Source)
            at org.gdg.frisbee.android.arrow.ArrowActivity.onOptionsItemSelected(ArrowActivity.java:146)
            at android.app.Activity.onMenuItemSelected(Activity.java:2856)
            at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:353)
            at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:144)
            at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:99)
            at android.support.v7.internal.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:99)
            at android.support.v7.internal.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:72)
            at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:164)
            at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:740)
            at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
            at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
            at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
            at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
            at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:598)
            at android.support.v7.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
            at android.view.View.performClick(View.java:5199)
            at android.view.View$PerformClick.run(View.java:21155)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5415)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:725)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:615)

**Comment by tasomaniac** [comment]
Nice bug. :smile:
