### ISSUE TITLE
Small bug introduced in 2.2

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/frisbee#453]
http://crashes.to/s/084e28f934d

**Comment by Splaktar** [comment]
For those without Crashlytics access:

    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.gdg.frisbee.android/org.gdg.frisbee.android.eventseries.TaggedEventSeriesActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.MenuItem.setChecked(boolean)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2417)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2477)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5415)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:725)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:615)
    Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.MenuItem.setChecked(boolean)' on a null object reference
       at org.gdg.frisbee.android.common.GdgNavDrawerActivity.setupDrawerContent(GdgNavDrawerActivity.java:153)
       at org.gdg.frisbee.android.common.GdgNavDrawerActivity.initNavigationDrawer(GdgNavDrawerActivity.java:119)
       at org.gdg.frisbee.android.common.GdgNavDrawerActivity.setContentView(GdgNavDrawerActivity.java:88)
       at org.gdg.frisbee.android.eventseries.TaggedEventSeriesActivity.onCreate(TaggedEventSeriesActivity.java:58)
       at android.app.Activity.performCreate(Activity.java:6162)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2370)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2477)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5415)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:725)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:615)

**Comment by tasomaniac** [comment]
Thank you. I was mobile :smile:
