### ISSUE TITLE
Crash: java.lang.IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by PareshMayani** [gdg-x/frisbee#581]
It's happening currently whenever I am trying to open "Android study jams", it might be happening due to the network fluctuation we are facing today but still it's a crash :)

```
org.gdg.frisbee.android.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: org.gdg.frisbee.android.debug, PID: 28850
                                                                               java.lang.IllegalArgumentException: Comparison method violates its general contract!
                                                                                   at java.util.TimSort.mergeLo(TimSort.java:761)
                                                                                   at java.util.TimSort.mergeAt(TimSort.java:497)
                                                                                   at java.util.TimSort.mergeCollapse(TimSort.java:424)
                                                                                   at java.util.TimSort.sort(TimSort.java:210)
                                                                                   at java.util.Arrays.sort(Arrays.java:1998)
                                                                                   at java.util.Collections.sort(Collections.java:1900)
                                                                                   at org.gdg.frisbee.android.eventseries.EventAdapter.sort(EventAdapter.java:172)
                                                                                   at org.gdg.frisbee.android.eventseries.TaggedEventSeriesFragment.sortEvents(TaggedEventSeriesFragment.java:179)
                                                                                   at org.gdg.frisbee.android.eventseries.TaggedEventSeriesFragment.access$100(TaggedEventSeriesFragment.java:46)
                                                                                   at org.gdg.frisbee.android.eventseries.TaggedEventSeriesFragment$1$1.onPutIntoCache(TaggedEventSeriesFragment.java:125)
                                                                                   at org.gdg.frisbee.android.cache.ModelCache$PutAsyncTask.onPostExecute(ModelCache.java:630)
                                                                                   at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                                   at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                                   at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

```

**Comment by friedger** [comment]
Does your location move around?

In `TaggedEventDistanceComparator` the location should be set once in the
constructor, or by a method before calling `sort` instead in all
comparisons. If the last location changes this could be the cause of the
mentioned exception.



[image: --]
Friedger Müffke
[image: http://]about.me/friedger
<http://about.me/friedger>


2016-03-16 11:23 GMT+01:00 Paresh Mayani <notifications@github.com>:

**Comment by tasomaniac** [comment]
Indeed we had a Feedback about this recently. I didn't experience the crash tho. 
We should fix this before release. 

What are the steps to reproduce it? Is it related to location? Should I try with location off?

**Comment by tasomaniac** [comment]
I disabled location and even removed location permission in Android M device. I couldn't make it crash :(

**Comment by friedger** [comment]
You have to change location while sorting

**Comment by tasomaniac** [comment]
How do I change the location while sorting?

**Comment by friedger** [comment]
Be lucky or on a flaky network? Or with constant changes via a mock
location provider?

My comments are only based on code inspection. Can reproduce either.

**Comment by tasomaniac** [comment]
But in the feedback we got in Doorbell says that it keeps crashing everytime they open that page.

**Comment by PareshMayani** [comment]
Yes it was crashing every time I tried to open "Android study jam"! Will check it again and try to reproduce the same issue.

**Comment by tasomaniac** [comment]
@friedger merged the fix. If @PareshMayani can confirm the fix, this can be closed.

**Comment by PareshMayani** [comment]
Yes I just tried to reproduce the crash with the apk shared by @tasomaniac in mail but not able to! Looks like it's fixed.
