### ISSUE TITLE
App ocasionaly crash on server response other than 200

### ISSUE THREAD

**Issue by przybylski** [gdg-x/frisbee#90]
It would require to add some sophisticated error handling in places where communication can fail

```
08-30 23:15:29.744: W/System.err(5991): com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
08-30 23:15:29.744: W/System.err(5991): {
08-30 23:15:29.744: W/System.err(5991):   "code": 400,
08-30 23:15:29.744: W/System.err(5991):   "errors": [
08-30 23:15:29.744: W/System.err(5991):     {
08-30 23:15:29.744: W/System.err(5991):       "domain": "usageLimits",
08-30 23:15:29.744: W/System.err(5991):       "message": "Bad Request",
08-30 23:15:29.744: W/System.err(5991):       "reason": "keyInvalid"
08-30 23:15:29.744: W/System.err(5991):     }
08-30 23:15:29.744: W/System.err(5991):   ],
08-30 23:15:29.744: W/System.err(5991):   "message": "Bad Request"
08-30 23:15:29.744: W/System.err(5991): }
08-30 23:15:29.744: W/System.err(5991): 	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:111)
08-30 23:15:29.744: W/System.err(5991): 	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:38)
08-30 23:15:29.744: W/System.err(5991): 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:312)
08-30 23:15:29.744: W/System.err(5991): 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1042)
08-30 23:15:29.744: W/System.err(5991): 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:410)
08-30 23:15:29.744: W/System.err(5991): 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
08-30 23:15:29.744: W/System.err(5991): 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
08-30 23:15:29.744: W/System.err(5991): 	at org.gdg.frisbee.android.fragment.InfoFragment$4.doInBackground(InfoFragment.java:180)
08-30 23:15:29.744: W/System.err(5991): 	at org.gdg.frisbee.android.fragment.InfoFragment$4.doInBackground(InfoFragment.java:171)
08-30 23:15:29.744: W/System.err(5991): 	at org.gdg.frisbee.android.task.CommonAsyncTask.doInBackground(CommonAsyncTask.java:79)
08-30 23:15:29.744: W/System.err(5991): 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
08-30 23:15:29.744: W/System.err(5991): 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
08-30 23:15:29.744: W/System.err(5991): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
```

**Comment by HenriqueRocha** [comment]
Is this still an issue? I've been using the app without API keys and it never crashed!
